server: ./CSD-D-JQR-Project-6-thread-pool/module_1/src/tpool.c ./server.c ./CSD-D-JQR-Project-6-thread-pool/module_1/src/queue.c ./worker.c
	gcc -g ./CSD-D-JQR-Project-6-thread-pool/module_1/src/tpool.c ./CSD-D-JQR-Project-6-thread-pool/module_1/src/queue.c ./server.c ./worker.c -o server -lpthread

client: ./client.c
	gcc -g client.c -o client